# Generated by Django 4.0.7 on 2022-09-08 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftsTv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=100)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WipTv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=100)),
                ('wip', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_api.line')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_api.shiftstv')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTargetsTv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('actual', models.IntegerField()),
                ('variance', models.IntegerField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_api.line')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_api.shiftstv')),
            ],
        ),
    ]
